# Generated by Django 6.0.1 on 2026-01-13 22:33

import django.utils.timezone
import generator.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('url', 'URL'), ('pdf', 'PDF'), ('image', 'Image')], max_length=10)),
                ('original_content', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=generator.models.upload_file_path)),
                ('qr_image', models.ImageField(upload_to=generator.models.qr_code_upload_path)),
                ('size', models.PositiveSmallIntegerField(default=10)),
                ('fill_color', models.CharField(default='#000000', max_length=7)),
                ('back_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='generator_q_created_f268a6_idx'), models.Index(fields=['content_type'], name='generator_q_content_fcd42c_idx')],
            },
        ),
    ]
